name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set up uv (fast Python package manager)
        uses: astral-sh/setup-uv@v3

      # Option 3: try venv first; if that fails, fall back to system install.
      - name: Ensure environment and install project
        run: |
          # Try to create a virtual environment (no-op if it already exists)
          uv venv || echo "Virtual env already exists or not supported."

          # Try installing into the venv; if it fails, install into the system
          uv pip install -e .[web] --link-mode=copy || uv pip install -e .[web] --system --link-mode=copy

      # Skip tests if the 'tests' directory does not exist
      - name: Run tests (if present)
        run: |
          if [ -d tests ]; then
            python -m unittest discover -s tests -t .
          else
            echo "No tests/ directory; skipping."
          fi

      - name: Build package with uv
        run: uv build

      - name: List build artifacts
        run: ls -lh dist

      # Optional: upload artifacts so you can download wheels/sdists from the CI run
      - name: Upload dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/**
